optimize: optimize echo case and upgrade dependency on netpoll
cloudwego/netpoll-examples pull request #6
Opened 2024-01-24 14:44 UTC by ning2510

#### What type of PR is this?

optimize
#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) Translate the PR title into Chinese.
优化 echo 例子，升级使用的 nepoll 版本

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

#### (optional) The PR that updates user documentation:

2024-01-25 09:05 UTC, joway requested changes

2024-01-25 09:05 UTC, joway commented on echo/client.go
> +	conn.SetOnRequest(func(ctx context.Context, connection netpoll.Connection) error {
client 正常的用法其实不会用 OnRequest ，考虑到这个example是给入门用的，所以还是不要用 OnRequest 来读取，直接 write 完后，再 read 会比较好。这也是典型的 client ping-pong 用法

2024-01-25 11:40 UTC, ning2510 commented on echo/client.go
> +	conn.SetOnRequest(func(ctx context.Context, connection netpoll.Connection) error {
Done

2024-01-26 02:39 UTC, joway approved these changes

2024-01-26 02:41 UTC, merged